/**
 * @file Automatically generated by barrelsby.
 */

export * from "./is-array";
export * from "./is-email";
export * from "./is-function";
export * from "./is-number-like";
export * from "./is-number";
export * from "./is-object";
export * from "./is-promise";
export * from "./is-string";
